### PR TITLE
Update git checkout branch before build

### PR DESCRIPTION
**Pull request by hsdk123**
Just making a PR for a bug I realised on the windows build when making the mac build.

### CODE REVIEW

**Comment by hsdk123** [comment]
@mosra How does this look?

**Comment by mosra** [comment]
What the heck is happening there :sweat_smile: 

@Squareys, why is there a checkout of master after the repo was cloned to a particular branch?

**Comment by Squareys** [comment]
I don't know... maybe the checkout can be removed entirely? Sorry about this.

**Comment by mosra** [comment]
Merged as 488b1e6a2bd1fd11668907d40a271ee9c5dcdf09, the checkout was unnecessary (and harmful) so I removed it altogether.

**Pull request closed without merging**
