### PR TITLE
Add Windows Action for Angle

### PR DESCRIPTION
**Pull request by Squareys**
Hi @mosra,

here's a start.

Cheers,
Jonathan

### CODE REVIEW

**Comment by mosra** [comment]
What the hell, you're too fast :rocket: 

Seeing the latest error, ff course their stuff is still stuck with python 2 :roll_eyes: 

Adding a link for myself: https://github.com/Squareys/magnum-ci/actions

**Comment by Squareys** [comment]
@mosra Already fixed the Python issue

**Comment by Squareys** [comment]
For documentation purposes:

Note the `ANGLE_VERSION` variable in `.github/workflows/windows.yml`, which checkes out the branch `chromium/${{ env.ANGLE_VERSION }}`.

**Comment by mosra** [comment]
Merged as ad7618c641dcc1a08c2fe47cd2c12862689cc2c3. Thanks a ton!

**Pull request closed without merging**
